In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import ast
pd.set_option('display.max_columns', None)

In [2]:
tiktok = pd.read_csv('tiktok_dataset.csv')
ig = pd.read_csv('insta_reels.csv')

In [3]:
tiktok.shape

(19382, 12)

In [4]:
ig.shape

(6790, 38)

In [5]:
tiktok.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0

In [6]:
#I'll drop the unwanted columns:
columns_to_drop_tiktok = ['#', 'claim_status', 'author_ban_status', 'video_id' ]
tiktok = tiktok.drop(columns=columns_to_drop_tiktok)

In [7]:
ig.head()

,inputUrl,id,type,shortCode,caption,hashtags,mentions,url,commentsCount,firstComment,latestComments,dimensionsHeight,dimensionsWidth,displayUrl,images,videoUrl,alt,likesCount,videoViewCount,videoPlayCount,timestamp,childPosts,ownerFullName,ownerUsername,ownerId,productType,videoDuration,isSponsored,taggedUsers,musicInfo,coauthorProducers,locationName,locationId,isPinned,paidPartnership,sponsors,error,description
0,https://www.instagram.com/turkialalshik,3.377458e+18,Video,C7fJFM_Sx01,Deontay Wilder’s right hand is out of this wor...,"['QueensberryVsMatchroom', '5vs5', 'RiyadhSeas...",['turkialalshik'],https://www.instagram.com/p/C7fJFM_Sx01/,96.0,نعم كلام صحيح، فإذا ضرب ديونتي ويلدر اي شخص بي...,"[{'id': '18023032144993896', 'text': 'نعم كلام...",1333.0,750.0,https://scontent.cdninstagram.com/v/t51.29350-...,[],https://scontent.cdninstagram.com/v/t50.2886-1...,NaN,10439.0,20250.0,98264.0,2024-05-27T21:14:07.000Z,[],DAZN Boxing,daznboxing,3.408672e+09,clips,20.431,False,[{'full_name': 'TURKI ALALSHIKH تركي آل الشيخ...,"{'artist_name': 'daznboxing', 'song_name': 'Or...","[{'id': '7020673524', 'is_verified': True, 'pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.instagram.com/jessandquinn,3.377480e+18,Video,C7fOC3oPkv2,…,"['comedy', 'funny', 'funnyvideos', 'viral', 'e...",[],https://www.instagram.com/p/C7fOC3oPkv2/,10.0,You look like you are dating Zendaya,"[{'id': '17983409876677583', 'text': 'You look...",1333.0,750.0,https://scontent.cdninstagram.com/v/t51.29350-...,[],https://scontent.cdninstagram.com/v/t66.30100-...,NaN,677.0,3406.0,13553.0,2024-05-27T22:02:01.000Z,[],Jess and Quinn,jessandquinn,5.655926e+10,clips,6.066,False,NaN,"{'artist_name': 'jessandquinn', 'song_name': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.instagram.com/jessandquinn,3.375973e+18,Video,C7Z3dgrvo0L,I am speed…,[],[],https://www.instagram.com/p/C7Z3dgrvo0L/,22.0,I can't do that but If I could...,"[{'id': '17878091439080353', 'text': ""I can't ...",1920.0,1080.0,https://scontent.cdninstagram.com/v/t51.29350-...,[],https://scontent.cdninstagram.com/v/t66.30100-...,NaN,2011.0,16248.0,40425.0,2024-05-25T20:07:09.000Z,[],Jess and Quinn,jessandquinn,5.655926e+10,clips,10.300,False,NaN,"{'artist_name': 'jessandquinn', 'song_name': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.instagram.com/aitym,3.375585e+18,Video,C7YfMnXCqgv,"“Когда руки в кp0Bи, запачкаться деpьMoм не пр...","['Бишимбаев', 'засалтанат', 'салтанат']",['aitym'],https://www.instagram.com/p/C7YfMnXCqgv/,93.0,👏,"[{'id': '17991000041643958', 'text': '👏', 'own...",1333.0,750.0,https://scontent.cdninstagram.com/v/t51.29350-...,[],https://scontent.cdninstagram.com/v/t66.30100-...,NaN,5256.0,128065.0,450969.0,2024-05-25T07:15:21.000Z,[],Timur Balymbetov,balukz,2.981418e+07,clips,55.866,False,"[{'full_name': 'Aitbek Amangeldi', 'id': '1975...","{'artist_name': 'balukz', 'song_name': 'Origin...","[{'id': '197584566', 'is_verified': True, 'pro...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.instagram.com/aitym,3.367975e+18,Video,C69c52WtqWX,15.05.1992 - ♾️❤️\nС днем рождения Салтик. \n\...,[],[],https://www.instagram.com/p/C69c52WtqWX/,13897.0,❤️,"[{'id': '17901891818913006', 'text': '❤️', 'ow...",1920.0,1080.0,https://scontent.cdninstagram.com/v/t51.29350-...,[],https://scontent.cdninstagram.com/v/t50.2886-1...,NaN,330885.0,2215143.0,5733459.0,2024-05-14T19:13:40.000Z,[],Фонд памяти Салтанат Нукеновой,saltanat.foundation,6.630578e+10,clips,85.400,False,"[{'full_name': 'Aitbek Amangeldi', 'id': '1975...","{'artist_name': 'saltanat.foundation', 'song_n...","[{'id': '197584566', 'is_verified': True, 'pro...","Astana, Kazakhstan",213709399.0,NaN,NaN,NaN,NaN,NaN

In [8]:
#I'll drop the unwanted columns:
columns_to_drop_ig = ['inputUrl', 'id', 'type', 'shortCode', 'url', 'firstComment', 'latestComments', 'dimensionsHeight', 'dimensionsWidth', 'displayUrl', 'images', 'videoUrl', 'alt', 'childPosts', 'ownerFullName', 'ownerUsername', 'ownerId', 'productType', 'isSponsored', 'taggedUsers', 'musicInfo', 'coauthorProducers', 'locationName', 'locationId', 'isPinned', 'paidPartnership', 'sponsors', 'error', 'description' ]
ig = ig.drop(columns=columns_to_drop_ig)

In [9]:
ig.head()

,caption,hashtags,mentions,commentsCount,likesCount,videoViewCount,videoPlayCount,timestamp,videoDuration
0,Deontay Wilder’s right hand is out of this wor...,"['QueensberryVsMatchroom', '5vs5', 'RiyadhSeas...",['turkialalshik'],96.0,10439.0,20250.0,98264.0,2024-05-27T21:14:07.000Z,20.431
1,…,"['comedy', 'funny', 'funnyvideos', 'viral', 'e...",[],10.0,677.0,3406.0,13553.0,2024-05-27T22:02:01.000Z,6.066
2,I am speed…,[],[],22.0,2011.0,16248.0,40425.0,2024-05-25T20:07:09.000Z,10.300
3,"“Когда руки в кp0Bи, запачкаться деpьMoм не пр...","['Бишимбаев', 'засалтанат', 'салтанат']",['aitym'],93.0,5256.0,128065.0,450969.0,2024-05-25T07:15:21.000Z,55.866
4,15.05.1992 - ♾️❤️\nС днем рождения Салтик. \n\...,[],[],13897.0,330885.0,2215143.0,5733459.0,2024-05-14T19:13:40.000Z,85.400

In [10]:
tiktok.isnull().sum()

video_duration_sec            0
video_transcription_text    298
verified_status               0
video_view_count            298
video_like_count            298
video_share_count           298
video_download_count        298
video_comment_count         298
dtype: int64

In [11]:
#since there's only 298 null values in multiple columns, I'll drop them
tiktok.dropna(subset=['video_view_count'], inplace=True)
tiktok.reset_index(drop=True, inplace=True)

In [12]:
ig.isnull().sum()

caption           334
hashtags            6
mentions            6
commentsCount       6
likesCount          6
videoViewCount      6
videoPlayCount    158
timestamp           6
videoDuration       6
dtype: int64

In [13]:
ig.dropna(subset=['hashtags'], inplace=True)
ig.reset_index(drop=True, inplace=True)

In [14]:
#since there's 152 null values in videoPlayCount, I'll fill them with the mean value
mean_play = ig['videoPlayCount'].mean() 
ig['videoPlayCount'].fillna(mean_play, inplace=True)

In [15]:
#the null values in the caption indicates that there's no caption added, so I'll fill them with 0
ig['caption'] = ig['caption'].fillna(0)

In [16]:
#I want to encode the 'verified_status' column to 0 and 1
display(tiktok['verified_status'].value_counts(dropna=False))
tiktok['verified_status'] = tiktok['verified_status'].map({'verified': 1, 'not verified': 0})

verified_status
not verified    17884
verified         1200
Name: count, dtype: int64

In [17]:
#I want to replace the values in 'hashtags' to be the number of hashtags
# Convert string representations of lists to actual lists
ig['hashtags'] = ig['hashtags'].apply(ast.literal_eval)

# Replace list values with the number of items in each list
ig['hashtags'] = ig['hashtags'].apply(lambda x: len(x) if isinstance(x, list) else 0)

In [18]:
#I want to replace the values in 'mentions' to be the number of mentions
# Convert string representations of lists to actual lists
ig['mentions'] = ig['mentions'].apply(ast.literal_eval)

# Replace list values with the number of items in each list
ig['mentions'] = ig['mentions'].apply(lambda x: len(x) if isinstance(x, list) else 0)

In [19]:
# Convert 'Timestamp' to datetime
ig['timestamp'] = pd.to_datetime(ig['timestamp'])

# Extract day of the week
ig['day'] = ig['timestamp'].dt.day_name()

# Extract date and time (hour and minute)
ig['time'] = ig['timestamp'].dt.strftime('%H:%M')

# Drop the original 'Timestamp' column
ig = ig.drop(columns=['timestamp'])

In [20]:
ig['time'] = pd.to_datetime(ig['time'], format='%H:%M')

# Extract hour and minute
ig['hour'] = ig['time'].dt.hour

# Drop the original 'time' column
ig = ig.drop(columns=['time'])

In [21]:
ig.head()

,caption,hashtags,mentions,commentsCount,likesCount,videoViewCount,videoPlayCount,videoDuration,day,hour
0,Deontay Wilder’s right hand is out of this wor...,3,1,96.0,10439.0,20250.0,98264.0,20.431,Monday,21
1,…,22,0,10.0,677.0,3406.0,13553.0,6.066,Monday,22
2,I am speed…,0,0,22.0,2011.0,16248.0,40425.0,10.300,Saturday,20
3,"“Когда руки в кp0Bи, запачкаться деpьMoм не пр...",3,1,93.0,5256.0,128065.0,450969.0,55.866,Saturday,7
4,15.05.1992 - ♾️❤️\nС днем рождения Салтик. \n\...,0,0,13897.0,330885.0,2215143.0,5733459.0,85.400,Tuesday,19

In [22]:
d_tiktok = tiktok.duplicated()
display(d_tiktok.value_counts(dropna=False))
#we have no duplicates in the tiktok dataframe

False    19084
Name: count, dtype: int64

In [23]:
d_ig = ig.duplicated()
display(d_ig.value_counts(dropna=False))
#we have no duplicates in the ig dataframe

False    6784
Name: count, dtype: int64

In [24]:
#unifying columns names
tiktok.rename(columns={'video_duration_sec': 'duration', 'video_transcription_text': 'caption', 'video_view_count': 'views', 'video_like_count': 'likes', 'video_share_count': 'shares', 'video_download_count': 'downloads', 'video_comment_count': 'comments'}, inplace=True)
ig.rename(columns={'commentsCount': 'comments', 'likesCount': 'likes', 'videoViewCount': 'views', 'videoPlayCount': 'plays', 'videoDuration': 'duration'}, inplace=True)

In [26]:
new_order_tiktok = ['views', 'duration', 'caption', 'verified_status', 'likes', 'comments', 'shares', 'downloads']

# Reorder the columns
tiktok = tiktok[new_order_tiktok]

new_order_ig = ['plays', 'duration', 'caption', 'mentions', 'hashtags', 'likes', 'comments', 'views', 'hour', 'day']

# Reorder the columns
ig = ig[new_order_ig]

In [27]:
tiktok.head()

,views,duration,caption,verified_status,likes,comments,shares,downloads
0,343296.0,59,someone shared with me that drone deliveries a...,0,19425.0,0.0,241.0,1.0
1,140877.0,32,someone shared with me that there are more mic...,0,77355.0,684.0,19034.0,1161.0
2,902185.0,31,someone shared with me that american industria...,0,97690.0,329.0,2858.0,833.0
3,437506.0,25,someone shared with me that the metro of st. p...,0,239954.0,584.0,34812.0,1234.0
4,56167.0,19,someone shared with me that the number of busi...,0,34987.0,152.0,4110.0,547.0

In [28]:
ig.head()

,plays,duration,caption,mentions,hashtags,likes,comments,views,hour,day
0,98264.0,20.431,Deontay Wilder’s right hand is out of this wor...,1,3,10439.0,96.0,20250.0,21,Monday
1,13553.0,6.066,…,0,22,677.0,10.0,3406.0,22,Monday
2,40425.0,10.300,I am speed…,0,0,2011.0,22.0,16248.0,20,Saturday
3,450969.0,55.866,"“Когда руки в кp0Bи, запачкаться деpьMoм не пр...",1,3,5256.0,93.0,128065.0,7,Saturday
4,5733459.0,85.400,15.05.1992 - ♾️❤️\nС днем рождения Салтик. \n\...,0,0,330885.0,13897.0,2215143.0,19,Tuesday

In [29]:
tiktok.to_csv('tiktok_cleaned.csv', index=False)
ig.to_csv('ig_cleaned.csv', index=False)